config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from permabots_www import views
from permabots_www.sitemaps import sitemaps
from django.contrib.sitemaps.views import sitemap

def uuidzy(url):
    return url.replace('%u', '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}')

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',content_type='text/plain')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    # User management
    url(r'^users/', include("permabots_www.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),
    # Your stuff: custom urls includes go here
    url(r'^processing/', include('permabots.urls_processing', namespace="permabots")),
    url(r'^api/v1/', include('permabots.urls_api', namespace="api")),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='pages/privacy_policy.html'), name="privacy-policy"),
    url(r'^docs/getting-started$', TemplateView.as_view(template_name='pages/getting-started.html'), name="getting-started"),
    url(r'^docs/api/', include('rest_framework_swagger.urls', namespace="swagger")),
    url(r'^bots/$', views.BotListView.as_view(), name="bot-list"),
    url(r'^bots/create/$', views.BotCreateView.as_view(), name="bot-create"),
    url(uuidzy(r'^bots/delete/(?P<pk>%u)/$'), views.BotDeleteView.as_view(), name="bot-delete"),
    url(uuidzy(r'^bots/update/(?P<pk>%u)/$'), views.BotUpdateView.as_view(), name="bot-update"),
    url(uuidzy(r'^bots/(?P<pk>%u)/$'), views.BotDetailView.as_view(), name="bot-detail"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/telegram/create/$'), views.TelegramBotCreateView.as_view(), name="bot-telegram-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/telegram/update/(?P<pk>%u)/$'), views.TelegramBotUpdateView.as_view(), name="bot-telegram-update"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/telegram/delete/(?P<pk>%u)/$'), views.TelegramBotDeleteView.as_view(), name="bot-telegram-delete"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/kik/create/$'), views.KikBotCreateView.as_view(), name="bot-kik-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/kik/update/(?P<pk>%u)/$'), views.KikBotUpdateView.as_view(), name="bot-kik-update"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/kik/delete/(?P<pk>%u)/$'), views.KikBotDeleteView.as_view(), name="bot-kik-delete"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/messenger/create/$'), views.MessengerBotCreateView.as_view(), name="bot-messenger-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/messenger/update/(?P<pk>%u)/$'), views.MessengerBotUpdateView.as_view(), name="bot-messenger-update"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/messenger/delete/(?P<pk>%u)/$'), views.MessengerBotDeleteView.as_view(), name="bot-messenger-delete"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/$'), views.HandlerListView.as_view(), name="handler-list"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/create/$'), views.HandlerCreateView.as_view(), name="handler-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/update/(?P<pk>%u)/$'), views.HandlerUpdateView.as_view(), name="handler-update"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/delete/(?P<pk>%u)/$'), views.HandlerDeleteView.as_view(), name="handler-delete"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/(?P<pk>%u)/$'), views.HandlerDetailView.as_view(), name="handler-detail"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/(?P<handler_pk>%u)/urlparams/create/$'), views.UrlParameterCreateView.as_view(), 
        name="handler-urlparameter-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/(?P<handler_pk>%u)/urlparams/update/(?P<pk>%u)/$'), views.UrlParameterUpdateView.as_view(), 
        name="handler-urlparameter-update"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/(?P<handler_pk>%u)/urlparams/delete/(?P<pk>%u)/$'), views.UrlParameterDeleteView.as_view(), 
        name="handler-urlparameter-delete"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/(?P<handler_pk>%u)/headerparams/create/$'), views.HeaderParameterCreateView.as_view(), 
        name="handler-headerparameter-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/(?P<handler_pk>%u)/headerparams/update/(?P<pk>%u)/$'), views.HeaderParameterUpdateView.as_view(), 
        name="handler-headerparameter-update"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/handlers/(?P<handler_pk>%u)/headerparams/delete/(?P<pk>%u)/$'), views.HeaderParameterDeleteView.as_view(), 
        name="handler-headerparameter-delete"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/$'), views.HookListView.as_view(), name="hook-list"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/create/$'), views.HookCreateView.as_view(), name="hook-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/update/(?P<pk>%u)/$'), views.HookUpdateView.as_view(), name="hook-update"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/delete/(?P<pk>%u)/$'), views.HookDeleteView.as_view(), name="hook-delete"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/(?P<pk>%u)/$'), views.HookDetailView.as_view(), name="hook-detail"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/(?P<hook_pk>%u)/recipients/telegram/create/$'), views.TelegramRecipientCreateView.as_view(), 
        name="hook-telegram-recipient-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/(?P<hook_pk>%u)/recipients/telegram/update/(?P<pk>%u)/$'), views.TelegramRecipientUpdateView.as_view(), 
        name="hook-telegram-recipient-update"),     
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/(?P<hook_pk>%u)/recipients/telegram/delete/(?P<pk>%u)/$'), views.TelegramRecipientDeleteView.as_view(), 
        name="hook-telegram-recipient-delete"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/(?P<hook_pk>%u)/recipients/kik/create/$'), views.KikRecipientCreateView.as_view(), 
        name="hook-kik-recipient-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/(?P<hook_pk>%u)/recipients/kik/update/(?P<pk>%u)/$'), views.KikRecipientUpdateView.as_view(), 
        name="hook-kik-recipient-update"),     
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/(?P<hook_pk>%u)/recipients/kik/delete/(?P<pk>%u)/$'), views.KikRecipientDeleteView.as_view(), 
        name="hook-kik-recipient-delete"),  
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/(?P<hook_pk>%u)/recipients/messenger/create/$'), views.MessengerRecipientCreateView.as_view(), 
        name="hook-messenger-recipient-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/(?P<hook_pk>%u)/recipients/messenger/update/(?P<pk>%u)/$'), views.MessengerRecipientUpdateView.as_view(), 
        name="hook-messenger-recipient-update"),     
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/hooks/(?P<hook_pk>%u)/recipients/messenger/delete/(?P<pk>%u)/$'), views.MessengerRecipientDeleteView.as_view(), 
        name="hook-messenger-recipient-delete"),  
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/env/$'), views.EnvironmentVarListView.as_view(), name="env-list"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/env/create/$'), views.EnvironmentVarCreateView.as_view(), name="env-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/env/update/(?P<pk>%u)/$'), views.EnvironmentVarUpdateView.as_view(), name="env-update"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/env/delete/(?P<pk>%u)/$'), views.EnvironmentVarDeleteView.as_view(), name="env-delete"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/env/(?P<pk>%u)/$'), views.EnvironmentVarDetailView.as_view(), name="env-detail"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/states/create/$'), views.StateCreateView.as_view(), name="state-create"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/states/update/(?P<pk>%u)/$'), views.StateUpdateView.as_view(), name="state-update"),
    url(uuidzy(r'^bots/(?P<bot_pk>%u)/states/delete/(?P<pk>%u)/$'), views.StateDeleteView.as_view(), name="state-delete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]
    
    urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]

permabots_www/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

permabots_www/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from rest_framework.authtoken.models import Token
from django.dispatch import receiver
from django.conf import settings

@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

permabots_www/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("bot-list")


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

permabots_www/templates/users/user_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}

{% if object == request.user %}
	<div class="section notopborder nomargin">

		<div class="container clearfix">

			<div class="col_one_fifth topmargin-sm nobottommargin">
				<h4>{% trans "Profile" %}</h4>
			</div>

			<div class="col_three_fifth nobottommargin col_last">
				<ul class="list-group">
					<li class="list-group-item"><b>Email address</b>
						<div class="fright">
							<a href="{% url 'account_email' %}"><i class="i-plain i-small icon-edit"></i></a>
						</div>
						<div class="fright rightmargin-sm">
								{{ object.email }}
						</div>
					</li>
					<li class="list-group-item"><b>Name</b> (Optional)

						<div class="fright">
							<a href="{% url 'users:update' %}"><i class="i-plain i-small icon-edit"></i></a>
						</div>
						<div class="fright rightmargin-sm">
								{{ object.name }}
						</div>
					</li>
				</ul>
			</div>

		</div>
	</div>
	
	<div class="section notopborder nomargin">

		<div class="container clearfix">

			<div class="col_one_fifth topmargin-sm nobottommargin">
				<h4>{% trans "Password" %}</h4>
			</div>

			<div class="col_three_fifth nobottommargin col_last">
					<div class="divcenter">
						<a href="{% url 'account_change_password' %}" class="button button-small button-border button-rounded"><i class="icon-edit"> Change</i></a>
					</div>
					</li>
					<div class="divcenter">
						<a href="{% url 'account_reset_password' %}" class="button button-small button-border button-rounded"><i class="icon-edit"> Reset</i></a>
					</div>
			</div>

		</div>
	</div>
	
	
	<div class="section  nomargin">

		<div class="container clearfix">

			<div class="col_one_fifth topmargin-sm nobottommargin">
				<h4>{% trans "API key" %}</h4>
			</div>

			<div class="col_three_fifth nobottommargin col_last">

					<ul class="list-group">
						<li class="list-group-item">
							<b>Token</b><div class="fright"><span class="badge">{{ object.auth_token }}</span></div>
						</li>
					</ul>
			</div>

		</div>
	</div>
{% endif %}
	

</div>
{% endblock content %}

permabots_www/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
<div class="divcenter nobottommargin clearfix" id="tab-login-register" style="max-width: 500px;">
	<div class="panel panel-default nobottommargin">
		<div class="panel-body" style="padding: 40px;">
    <h1>{{ user.email }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="button button-small button-border button-rounded">Update</button>
          </div>
        </div>
    </form>
    </div>
    </div>
    </div>
{% endblock %}

permabots_www/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

</div>

{% endblock content %}